### ISSUE TITLE
Examples build correctly but won't load

### ISSUE THREAD

**Issue by DeRobyJ** [pure-data/externals-howto#13]
Using msys2/mingw-w64 on Windows 10 64bit. Puredata vanilla 0.50.2

I built the example1, and it doesn't load on puredata (I've checked the helloworld.dll it's on the right folder).
Tried building example2 (counter) too, but again pd sends a "... couldn't create" error.

I'm sure my puredata installation is 64bit, as the windows Task Manager doesn't print the "(32bit)" line after the app name.

Should I downgrade to a previous puredata version?
Anything else I can do to build the objects correctly?

`++++ info: using Makefile.pdlibbuilder version 0.5.1`
`++++ info: using Pd API D:/Programmi/puredata/pd-0.50-2/src/m_pd.h`
`++++ info: making target all in lib externals.howto.example2`
`++++ info: making counter.o in lib externals.howto.example2`
`gcc -DPD -I "D:/Programmi/puredata/pd-0.50-2/src" -DMSW -DNT     -Wall -Wextra -Wshadow -Winline -Wstrict-aliasing -O3 -ffast-math -funroll-loops -fomit-frame-pointer -march=core2 -msse -msse2 -msse3 -mfpmath=sse -o counter.o -c counter.c`
`++++ info: linking objects in counter.dll for lib externals.howto.example2`
`gcc -static-libgcc -shared -Wl,--enable-auto-import "D:/Programmi/puredata/pd-0.50-2/bin/pd.dll"    -o counter.dll counter.o `

`++++info: target all in lib externals.howto.example2 completed`

**Comment by danomatika** [comment]
Ping @Spacechild1

**Comment by Spacechild1** [comment]
Works here with msys2, Windows 7, Pd 0.50 64 bit.

> I've checked the helloworld.dll it's on the right folder

which folder? did you add the folder to the search paths (either in preferences or with `[declare]`)?

Here's a trick: try to create the object with an *absolute* file path, e.g. "C:/myrepos/externals-howto/example1/helloworld". If this works, then you know you have a path problem and you can do what @umlaeute suggested below.

**Comment by umlaeute** [comment]
run Pd in `verbose` mode (`File->Preferences->Path...`, tick the `verbose` checkbox), and see where it searches for the external.

**Comment by DeRobyJ** [comment]
Nope, doesn't look like a path problem. However there's something going on with slashes.

`tried D:/Docs/puredata/externals/counter.dll and succeeded`
`D:\Docs\puredata\externals\counter.dll: couldn't load`

![image](https://user-images.githubusercontent.com/6437521/67384639-d854a600-f591-11e9-81f6-7bf4c30dd6e5.png)



@Spacechild1

![image](https://user-images.githubusercontent.com/6437521/67384829-2ec1e480-f592-11e9-9ac8-8adea99764a8.png)

**Comment by Spacechild1** [comment]
can you try my build?

[counter.zip](https://github.com/pure-data/externals-howto/files/3761985/counter.zip)

**Comment by Spacechild1** [comment]
the slashes are fine. "couldn't load" means that `LoadLibrary` failed. (It would be helpful if it would print the error code).

**Comment by Spacechild1** [comment]
Can you verify you external DLL is really 64-bit? Are you sure you're compiling from the "MSYS2 MINGW64" shell?

**Comment by DeRobyJ** [comment]
Your counter works, and it's **twice the size as mine**! (296KB vs 122KB)
Up until now I've used the msys2.exe terminal, while I've now tried using the mingw64.exe one

but unfortunately results are the same.
And it's right, as I couldn't have used a 64bit pd.dll for building!
(I once tried using the original msys, a 32bit terminal, and it failed because of that)


> Can you verify you external DLL is really 64-bit? 

not sure what you are referring to, here

**Comment by DeRobyJ** [comment]
Just to _make_ sure, here's my make command
`make PDINCLUDEDIR=D:/Programmi/puredata/pd-0.50-2/src PDBINDIR=D:/Programmi/puredata/pd-0.50-2/bin`

**Comment by Spacechild1** [comment]
looks good. actually, this works as well: `make PDDIR=D:/Programmi/puredata/pd-0.50-2`

Considering your other issue (`__int64` not recognized), I think your Msys2 setup is broken... Maybe reinstall from scratch. People have been successfully compiling 64-bit Pd + externals with Msys2 for some time now.

EDIT: fixed typo in `PDDIR=`

**Comment by DeRobyJ** [comment]
Mh.. Ok to me, I can try it, but I've actually installed this configuration two days ago, and I only used pacman to install make and gcc.

I used the msys2-x86_64-20190524.exe installer.

Are you using the same version? I could try to switch it.
These are my make and gcc versions:
![image](https://user-images.githubusercontent.com/6437521/67390098-39817700-f59c-11e9-85cb-4dde7a770167.png)

Any differences here?

_____________________________________

> this works as well: make PDIDIR=D:/Programmi/puredata/pd-0.50-2

For some reason, it doesn't, it still searched the m_pd.h in the default folder

**Comment by Spacechild1** [comment]
> For some reason, it doesn't, it still searched the m_pd.h in the default folder

ugh, because I made a typo, should read: `PDDIR=`

please use the MINGW64 shell. My 64-bit GCC version is 9.1.0

> and I only used pacman to install make and gcc.

how did you install? it's recommended to install the toolchains, i.e.

`pacman -S mingw-w64-i686-toolchain` for the 32-bit toolchain
and
`pacman -S mingw-w64-x86_64-toolchain` for the 64-bit toolchain

**Comment by Spacechild1** [comment]
BTW, can you post the binaries you've compiled? would be interesting to see why they don't work.

**Comment by DeRobyJ** [comment]
Sure thing:
[counter.zip](https://github.com/pure-data/externals-howto/files/3762220/counter.zip)



Currently starting from scratch and following your suggestions, I'll be back shortly.

**Comment by DeRobyJ** [comment]
Yup, it now works.

Installed from [msys2-x86_64-20190524.exe](https://www.msys2.org/)
Using the mingw64.exe terminal.
running:
`pacman -S mingw-w64-x86_64-toolchain` 
(install everything, as per default)
`pacman -S make` 
(make-4.2.1-1)

On Windows 10 64bit
[Pd vanilla 0.50-2](http://msp.ucsd.edu/software.html)


Thanks a lot
