### ISSUE TITLE
linking doesn't work on osx 10.14.5

### ISSUE THREAD

**Issue by mdedwards** [pure-data/externals-howto#14]
anyone else seeing this when trying to compile example1?

~~~
++++ info: linking objects in helloworld.pd_darwin for lib externals.howto.example1
cc -undefined suppress -flat_namespace -bundle  -arch i386 -arch x86_64 -mmacosx-version-min=10.5  -o helloworld.pd_darwin helloworld.o  -lc   
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [helloworld.pd_darwin] Error 1
~~~

**Comment by danomatika** [comment]
Are you overriding the defaults somewhere? On 10.14, you cannot build 32 bit, so `-arch i386` should result in an error. Also, the min version is recommended to be 10.6.

**Comment by danomatika** [comment]
I see the same on 10.14 and it's related to pdlibbuilder being out of date, ala #11.

**Comment by danomatika** [comment]
Latest commits update to pdlibbuilder 0.6.0.

**Comment by mdedwards** [comment]
wow! that was quick! I wasn't knowingly overriding defaults. Many thanks for this

**Comment by danomatika** [comment]
It was easy and we should have done it once old-lib-builder 0.6.0 was finished anyway.

**Comment by mdedwards** [comment]
nevertheless, the speed helps. it now compiles but PD spits out "load_object: Symbol "mdeGranular_tilde_setup" not found"

back to the drawing board. i last ran this code in 2003!

**Comment by danomatika** [comment]
That's the setup function name exposed by the external, but it might have a different name or be static in the .c implementation. You might need to remove the static keyword or name a function of that name which inits the external.

**Comment by mdedwards** [comment]
i've got that defined in a separate file. the external has been running for years in maxmsp so i have a platform independent file then pd and max files separately. i don't seem to be getting the pd file to be compiled and linked. i must be being dumb in my makefile:

```
# library name
lib.name = mdegranular~

# common.sources = mdegranular~.c 
lib.setup.sources = mdeGranular~pd.c

# input source file (class name == source file basename)
class.sources = mdeGranular~.c


# all extra files to be included in binary distribution of the library
datafiles =

# include Makefile.pdlibbuilder from submodule directory 'pd-lib-builder'
PDLIBBUILDER_DIR=./externals-howto/pd-lib-builder
include $(PDLIBBUILDER_DIR)/Makefile.pdlibbuilder

```

**Comment by danomatika** [comment]
I don't know the details, really. Someone else could better answer this on the pd-list. My quick suggestion was: "Pd needs a function named _mdeGranular_tilde_setup_ so try adding that function to your source file and have it wrap whatever the actual setup function is named."

**Comment by mdedwards** [comment]
gotcha thanks dan
