### ISSUE TITLE
pan~ should be called xfade~

### ISSUE THREAD

**Issue by gzalles** [pure-data/externals-howto#7]
Small detail, you actually made a crossfade external not a panner. 

I think renaming it makes it clearer.

Cheers

**Comment by adammccartney** [comment]
Yes, would make the tutorial a bit clearer if its functionality was correctly named.

**Comment by umlaeute** [comment]
how much clearer?

on a scale from 0 to 10 (with 0 being total muddle, and 10 being enlightenment), how would you rate the clearness of the tutorial as it is now?
on the same scale, how would you rate it with this name-change?

(i'm mostly taking the opportunity to get feedback on the quality of the tutorial itself)

**Comment by adammccartney** [comment]
The tutorials are really excellent, now that you mention it, there is something of a zen koan quality to it as is!
At the moment, let's say 7 or 8/10. Solid 9/10 with the name change
